#!/bin/bash
# See CONTRIBUTING.md for usage.

set -x

TAG="docker-compose:$(git rev-parse --short HEAD)"
TOX_MOUNT=$(docker run -d -v "$(pwd)/.tox:/code/.tox" busybox /bin/true)

docker build -t "$TAG" . && \
docker run \
  --rm \
  --volume="/var/run/docker.sock:/var/run/docker.sock" \
  --volume="$(pwd):/code" \
  -e DOCKER_VERSIONS \
  -e "TAG=$TAG" \
  -e "TOX_MOUNT=$TOX_MOUNT" \
  --entrypoint="script/test-versions" \
  "$TAG" \
  "$@"

docker stop $TOX_MOUNT && docker rm $TOX_MOUNT
