#!/bin/bash

set -e

BUILD_ID="swarm${BUILD_NUMBER-$USER}"
COMPOSE="docker-compose -f tests/environment/swarm.yml -p ${BUILD_ID}"

$COMPOSE up -d

function on_exit() {
    $COMPOSE stop
    $COMPOSE rm -f
}
trap "on_exit" EXIT


network="${BUILD_ID}_default"
ip=$(docker inspect -f "{{.NetworkSettings.Networks.${network}.IPAddress}}" ${BUILD_ID}_swarm.master_1)


echo "Using host $ip"
export DOCKER_HOST="tcp://$ip:2375"
timeout 30 tests/environment/wait_on_swarm

export IS_SWARM_TEST=1
tox -e py27
